ALTER TABLE "User"
ADD COLUMN "radarMinMarketCap" DOUBLE PRECISION NOT NULL DEFAULT 3000000,
ADD COLUMN "radarMaxMarketCap" DOUBLE PRECISION,
ADD COLUMN "radarMinTurnoverPercent" DOUBLE PRECISION NOT NULL DEFAULT 15,
ADD COLUMN "radarMinVolumeAcceleration" DOUBLE PRECISION,
ADD COLUMN "radarMinPriceChange24h" DOUBLE PRECISION,
ADD COLUMN "radarMinTradeCount24h" INTEGER;
