ALTER TABLE "User"
ADD COLUMN "radarIncludeLowCap" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "radarIncludeMidCap" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "radarIncludeHighCap" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "radarIncludeDex" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "radarIncludeCex" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "radarMinDexVolumeUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;
